//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Department Department1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
